### ISSUE TITLE
Cannot load resources when using account with access to multiple tenants

### ISSUE THREAD

**Issue by Agazoth** [microsoft/vscode-azureresourcegroups#833] opened 2024-03-26 07:20 UTC
Does this occur consistently? Yes
Repro steps:

1. Log on to the main tenant
2. Select a subscription

![image](https://github.com/microsoft/vscode-azureresourcegroups/assets/15127301/5bb18055-6002-40f9-be17-c515e47141f3)

I use my azure account to log in to my main tenant. I use the same account to log on to another tenant, where my account is invited as guest account and made member.

When I connect to my main tenant, Logic Apps and Integration Accounts load by selected subscription as expected. But refreshing the Resources group generates this toast:
![image](https://github.com/microsoft/vscode-azureresourcegroups/assets/15127301/25e1c641-feb9-4bf8-a804-fdc815748930)

Version: 0.8.4
OS: win32
OS Release: 10.0.22621
Product: Visual Studio Code
Product Version: 1.87.1
Language: en

**Comment by alexweininger** [comment] 2024-04-03 17:44
Closing as duplicate of #834

**Closed by alexweininger** 2024-04-03 17:44 UTC
