### ISSUE TITLE
`onTreeItemCreate` accessor should never be called.

### ISSUE THREAD

**Issue by bwateratmsft** [microsoft/vscode-azureresourcegroups#538] opened 2023-01-31 18:05 UTC
From @jongio originally. Upon clicking the "Deploy..." button on the Workspace view, this error shows: 

> `onTreeItemCreate` accessor should never be called.

Looks like all of the core Azure extensions are present.

**Comment by alexweininger** [comment] 2023-01-31 19:21
Closing as this is caused by using v1 extensions with RGs v2.

**Closed by alexweininger** 2023-01-31 19:21 UTC
Labels: 🐛bug
