### ISSUE TITLE
The previous focused resource group displays shortly in the FOCUSED RESOURCES view when focusing a resource group

### ISSUE THREAD

**Issue by v-xinda** [microsoft/vscode-azureresourcegroups#732] opened 2023-07-28 06:37 UTC
**OS:** Win10/M1 
**Build Version:** 20230727.1
**Regression:** Not a regression

**Repro Steps:**

1. Click "Focus Group" icon to focus a resource group -> Unfocus it.
2. Click "Focus Group" icon to focus another resource group.
3.  Check whether the previous focused resource group doesn't display in the FOCUSED RESOURCES view.

**Expect:**
The previous focused resource group doesn't display in the FOCUSED RESOURCES view.

**Actual:**
The previous focused resource group displays in the FOCUSED RESOURCES view.
![actual3](https://github.com/microsoft/vscode-azureresourcegroups/assets/57662131/7d2aef26-1a43-4de2-9f3c-edc50146d182)

**Comment by MicroFish91** [comment] 2023-08-02 22:18
It's a good catch, but probably not worth the amount of time and effort required to make this fix, closing by design

**Closed by MicroFish91** 2023-08-02 22:18 UTC
Labels: AT-CTI
