### ISSUE TITLE
g[Symbol.iterator] is not a function error when expanding Subscription

### ISSUE THREAD

**Issue by bpsims** [microsoft/vscode-azureresourcegroups#296] opened 2022-06-07 18:39 UTC
After signing into Azure, expanding the Subscription name will throw a "g[Symbol.iterator] is not a function" error and no resources will load under the headings.  I believe this started happening within the past week. 

Windows 10
Azure Stack tenant

Another error shows up in the console:
ERR [Extension Host] (node:45396) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.

**Comment by alexsmithMSFT** [comment] 2022-07-08 15:32
Issue does not repro in older version https://github.com/microsoft/vscode-azureresourcegroups/releases/tag/v0.4.0
Recommend using version 0.4.0 until the issue is fixed in 0.5.X or later versions.

**Comment by bpsims** [comment] 2022-07-11 21:30
Installed 0.4.0 which does fix the resources listing. But it breaks the "Azure Functions" and "Azure App Service" extensions  (and possibly others) with an error that the azureresourcegroups extension must be updated.  I've tried rolling those two extensions back to previous versions as well but each versions seems to fail in one way or another. 
i.e. "Cannot read properties of undefined (reading 'tree')"

**Closed** 2022-07-12 17:26 UTC
Labels: bug, feature

**Comment by alexweininger** [comment] 2022-07-13 21:03
Verified fix with user offline. 💯
