### ISSUE TITLE
Fail to execute command "Azure Resources Group: Focus this Group" again for the same group on M1

### ISSUE THREAD

**Issue by v-mengwe** [microsoft/vscode-azureresourcegroups#226] opened 2022-05-06 09:03 UTC
**OS:** M1
**Azure Resource Extension Build Version:** 20220505.12 (unified)
**Regression:** 20220503.22

**Repro Steps:**

1. F1 -> Azure Resources Group: Focus this Group -> Select a subscription -> Select a group.
2. F1 -> Azure Resources Group: Unfocus Group.
3. F1 -> Azure Resources Group: Focus this Group -> Select a subscription -> Select the group in step 1 again.
4. Check whether succeeds to execute command "Azure Resources Group: Focus this Group" or not.

**Expect:**
Succeed to execute command "Azure Resources Group: Focus this Group".

**Actual:**
Fail to execute command "Azure Resources Group: Focus this Group".

**More Info:**
This issue does not reproduce on Linux/Windows OS.

**Comment by alexweininger** [comment] 2022-05-06 23:14
I can't reproduce this or https://github.com/microsoft/vscode-azureresourcegroups/issues/225 on my Intel mac, so this might actually be specific to M1. Super weird.

**Comment by alexweininger** [comment] 2022-05-11 19:33
Fixed by https://github.com/microsoft/vscode-azureresourcegroups/pull/236

**Closed by alexweininger** 2022-05-11 19:33 UTC
Labels: AT-CTI, unified
