### ISSUE TITLE
Newly created resource group looks different from existing RGs

### ISSUE THREAD

**Issue by wwlorey** [microsoft/vscode-azureresourcegroups#169] opened 2022-04-13 20:29 UTC
My dope, special RG I just created has a different icon and also says how many resources it contains, while existing ones don't.

<img width="380" alt="Screen Shot 2022-04-13 at 1 27 28 PM" src="https://user-images.githubusercontent.com/22795803/163264726-c96f4fd3-e241-4083-a3a1-3abca460e0a1.png">

**Comment by wwlorey** [comment] 2022-04-13 20:30
(I'm assuming these discrepancies don't have anything to do with my RG being dope or special)

**Comment by wwlorey** [comment] 2022-04-14 20:20
This reproduced when creating a function app (via the "Create Function" command):
![Screen Shot 2022-04-14 at 1 19 57 PM](https://user-images.githubusercontent.com/22795803/163469223-e790dfc7-3da9-49ff-8cd6-b9b6313d977f.png)

**Comment by nturinski** [comment] 2022-04-14 21:04
Hah this is a pretty dope find.

**Comment by alexweininger** [comment] 2022-04-14 21:59
Duplicate of #162!!! 😄 🤠  And fixed by #161 and #163 🚀

**Closed by alexweininger** 2022-04-14 21:59 UTC
Labels: unified
