### ISSUE TITLE
The "Group By" icon disappears from the resources view after installing both Azure Function extension and App Service extension

### ISSUE THREAD

**Issue by v-ruizh** [microsoft/vscode-azureresourcegroups#352] opened 2022-07-29 09:58 UTC
**OS:** Win10
**App Service Extension Build Version:** 20220729.1
**Azure Function Extension Build Version:** 20220729.3
**VS Code Insider Build:**
![image](https://user-images.githubusercontent.com/45614674/181734544-4f0e9a8e-43c1-417e-a5fa-11e7996a08b3.png)

**Repro Steps:**
1. Install Azure Function extension in **VS Code Insiders**.
2. Install App Service extension in **VS Code Insiders**.
3. Navigate to Azure View.
4. Check whether the "Group By" icon shows in the resources view.

**Expect:**
The "Group By" icon shows in the resources view.
![image](https://user-images.githubusercontent.com/45614674/181734845-be53e620-63cb-421c-a5c6-500d1ec0d8f6.png)

**Actual:**
The "Group By" icon disappears from the resources view.
![image](https://user-images.githubusercontent.com/45614674/181734822-f11c6ae3-8061-425a-b050-d15b71248f1e.png)

**More Info:**
1. This issue does not reproduce if only install one extension (Azure Function or App Service).
2. This issue does not reproduce in **VS Code**.

**Comment by alexweininger** [comment] 2022-08-03 22:25
Duplicate of #330

**Closed by alexweininger** 2022-08-03 22:25 UTC
Labels: bug, AT-CTI
