### ISSUE TITLE
Navigate to the Explorer view after unfocusing the resource from the FOCUSED RESOURCES view

### ISSUE THREAD

**Issue by v-xinda** [microsoft/vscode-azureresourcegroups#691] opened 2023-05-18 08:27 UTC
**OS:** Mac
**Build Version:** 20230518.3
**Regression:** Not a Regression

**Repro Steps:**

1. Click the magnifying glass icon to focus a resource group.
2. Click the "Unfocus Group" icon in the FOCUSED RESOURCES view.
3. Check whether navigate to the Azure view.

**Expect:**
Navigate to the Azure view.

**Actual:**
Navigate to the Explorer view.
https://github.com/microsoft/vscode-azureresourcegroups/assets/57662131/e3f26a90-7949-4909-9b3e-67af33594a3e

**More Info:**
This issue doesn't reproduce on the Windows and Linux platforms.

**Comment by MicroFish91** [comment] 2023-06-14 22:41
We were able to reproduce this on Windows as well.

Since you had previously split the focus view into a new pane, when the pane was exited it just goes back to the previous pane.  Closing this as by designed.

**Closed by MicroFish91** 2023-06-14 22:41 UTC
Labels: enhancement, AT-CTI
