### ISSUE TITLE
Unified: Error when expanding on Azure subscription

### ISSUE THREAD

**Issue by jinglouMSFT** [microsoft/vscode-azureresourcegroups#156] opened 2022-04-07 00:44 UTC
OS: Windows 10
VS Code:  Insider v1.67.0 & stable v1.66.0
Resource Group extension from: #20220405.3 Add display names and icons (#148)
Azure account extension: v0.10.0

Note:  I previously had the old release of the Resource Group extension installed, as well as the static web app extension installed. I uninstalled both. Then perform the following steps.

Repro:
1. In VS Code, F1 to bring up command prompt and search for Extension: install from VSIX.  Select the VSIX downloaded from the above build
2. Since my last Azure login session was from a long time ago, the resource extension couldn't be activated using the old authentication. I had to reauthenticate to sign into Azure which was successful, and my subscription was shown in the resource group
3. Try to expand the subscription node

Expected Results:
Show my Azure resources, or no error if I don't have any Azure resources

Actual Result:
"Error: Cannot read properties of undefined (reading 'id')

![image](https://user-images.githubusercontent.com/10081483/162097764-a4c1ed3b-d5d3-4a1b-93a0-95e32eb73368.png)

Account extension configuration:
![image](https://user-images.githubusercontent.com/10081483/162098052-5423c2c9-cdad-4495-87f9-ad94efdddf79.png)

Also FYI, this happened to all subscriptions I know I have access to or I am a owner of.

**Comment by alexweininger** [comment] 2022-04-07 23:06
Caused by the `groupBy` setting not respecting the default value somehow.

Repro steps:
1. Install extension from VSIX
2. Go to your settings.json file, and delete the `groupBy` setting
3. Reload VS Code or refresh the tree

We have a default value specified in the package.json, not sure why VS Code gives us undefined instead of this value...

**Comment by nturinski** [comment] 2022-04-20 20:32
Fixed by https://github.com/microsoft/vscode-azureresourcegroups/pull/159

**Closed by nturinski** 2022-04-20 20:32 UTC
Labels: unified
