### ISSUE TITLE
No resource shows in the resource group

### ISSUE THREAD

**Issue by v-xinda** [microsoft/vscode-azureresourcegroups#573] opened 2023-02-15 08:08 UTC
**OS:** All
**Resource Group Build Version:** 20230214.5
**Azure Container App Build Version:** 20230213.10

**Repro Steps:**

1. F1 -> Azure: Delete Resource Group... -> Select subscription -> Select a resource group such as "Nicole-env2".
2. Pop up a delete confirmation "There is 1 resource in this resource group that will be deleted." -> Click "Cancel".
3. Expand the resource group "Nicole-env2".
4. Check whether one resource shows in this resource group.

**Expect:**
One resource shows in this resource group.
<img width="641" alt="Screenshot 2023-02-15 at 15 07 04" src="https://user-images.githubusercontent.com/57662131/218956712-6f41fc66-b5c6-4e3d-b742-a8b433bcdd4d.png">

**Actual:**
No resource shows in this resource group.
<img width="400" alt="Screenshot 2023-02-15 at 14 51 10" src="https://user-images.githubusercontent.com/57662131/218956465-4582c0bb-7abf-4dfb-83cb-290749f6575e.png">

**Comment by alexweininger** [comment] 2023-02-15 22:20
I think this is expected behavior, since we're just no longer showing the filtered resources unless they enable the `azureResourceGroups.showHiddenTypes` setting.

**Comment by alexweininger** [comment] 2023-02-15 23:14
Closing as this is by design.

**Closed by alexweininger** 2023-02-15 23:14 UTC
Labels: AT-CTI
