### ISSUE TITLE
No error dialog pops up when second updating tags with invalid tags

### ISSUE THREAD

**Issue by v-mengwe** [microsoft/vscode-azureresourcegroups#27] opened 2020-06-30 09:11 UTC
**OS:** Win10
**Build Version:** 20200628.1

**Repro Steps:**

1. Right click one resource group --> Select "Edit Tags..." --> Add tags and save the file.
2. The first update is successful.
3. Change the tag has problem, such as:
![image](https://user-images.githubusercontent.com/62053665/86103911-f2b32c00-baef-11ea-8b5a-c5e6ea68768b.png)
5. Ctrl+S

**Expect:**
Pop up an error, such as:
![image](https://user-images.githubusercontent.com/62053665/86103388-47a27280-baef-11ea-93af-b09e61ead0f1.png)

**Actual:**
There is no error and pop up a notification about "Successfully updated tags for resource group..."
![image](https://user-images.githubusercontent.com/62053665/86103404-4c672680-baef-11ea-8d15-07f46f41325b.png)

**Comment by EricJizbaMSFT** [comment] 2020-06-30 17:25
This is actually a duplicate of https://github.com/microsoft/vscode-azureresourcegroups/issues/18. The problem is that any error coming from 'jsonc' (as seen in the problems view) does not block upload

**Closed by EricJizbaMSFT** 2020-06-30 17:25 UTC
Labels: AT-CTI
