### ISSUE TITLE
An error occurs after executing "Azure: Group by ARM Tag..." action

### ISSUE THREAD

**Issue by v-xinda** [microsoft/vscode-azureresourcegroups#473] opened 2022-12-26 10:18 UTC
**OS:** Win10
**Build Version:** Azure Resources v0.5.7-alpha.0

**Repro Steps:**
1. F1 -> Click "Azure: Group by ARM Tag...".
2. Check whether no error occurs.

**Expect:**
No error occurs.

**Actual:**
An error occurs.
![image](https://user-images.githubusercontent.com/57662131/209537495-3100956a-0fe4-42ba-96ae-400dea4e8949.png)

**More Info:**
This issue doesn't reproduce when executing commands "Azure: Group by Resource Group/ Location/ Resource Type".

**Comment by alexweininger** [comment] 2023-01-11 00:29
Duplicate of #465

**Closed by alexweininger** 2023-01-11 00:29 UTC
Labels: AT-CTI, hostapi-v2
