### ISSUE TITLE
[Unstable] An error pops up after clicking "+" to create a resource

### ISSUE THREAD

**Issue by v-xinda** [microsoft/vscode-azureresourcegroups#368] opened 2022-08-19 10:02 UTC
**OS:** Win 10
**Build Version:** 20220818.5
**VS Code insider version:** 1.71.0-insider (user setup)

**Repro Steps:**
1. Click "+" -> Click "Create Resource Group...".
2. Check whether no error pops up.

**Expect:**
No error pops up.

**Actual:**
An error pops up.
![image](https://user-images.githubusercontent.com/57662131/185593314-356b7ec7-b1da-41c0-ab6a-fa3ae5e8c2a3.png)

**More Info:**
This issue also reproduces when clicking "+" to create other resources.

**Comment by alexweininger** [comment] 2022-08-24 22:00
Release of the feature that causes this bug is being delayed until September https://github.com/microsoft/vscode/issues/42903#issuecomment-1225956482

**Comment by alexweininger** [comment] 2022-08-24 22:20
We can edit the create resource command in resource groups to fix this specific bug. And as we release extensions, we can properly respond to this change for other commands if needed.

**Comment by alexweininger** [comment] 2022-08-24 22:25
Duplicate of #363

**Closed by alexweininger** 2022-08-24 22:25 UTC
Labels: 🐛bug, AT-CTI
