### ISSUE TITLE
Unable to create a resource through vscode

### ISSUE THREAD

**Issue by niles87** [microsoft/vscode-azureresourcegroups#360] opened 2022-08-12 22:06 UTC
Does this occur consistently? Yes
Repro steps:

1. Sign into Azure successfully 
2. click add resource and choose Create Function App 
3. follow steps to complete creating a resource

**Expected Result**
Have a created resource on Azure as well as viewable resource in vsCode panel.

**Actual Result**
 Following error message
`Subscription <subscription id> was not found.`

Version: 0.5.5
OS: darwin
OS Release: 21.6.0
Product: Visual Studio Code
Product Version: 1.70.1
Language: en

**Comment by alexweininger** [comment] 2022-08-17 22:17
What kind of subscription were you signed in with? Any chance you're using a sandbox subscription?

**Comment by niles87** [comment] 2022-08-17 23:26
I don't believe so, my account type is a Microsoft Customer Agreement.
I am able to create a Function App in portal and deploy the project through vsCode. I'm just unable to create a Function App resource.

**Comment by alexweininger** [comment] 2022-09-21 22:13
This has been fixed in Azure Functions v1.8.0 https://github.com/microsoft/vscode-azurefunctions/releases/tag/v1.8.0

Duplicate of https://github.com/microsoft/vscode-azurefunctions/issues/3269

**Closed by alexweininger** 2022-09-21 22:13 UTC
Labels: 🔎 investigate 🕵️
